# Site settings
title: "Sinnix"
description: "Sinnix web page."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sinnix"
resume_title:                   "Florian Miess"

# used for the contact button in _layouts/resume.html
#resume_contact_email:           "florian.miess ät sinnix.de"

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone:       "+49.178.8583322"
#resume_contact_address:         "Adresse"

resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: "<br>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank


# Decide which sections to use
# comment out to hide
resume_section_experience:      false
github_blog :                   true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/hamiller"
  resume_twitter_url:           "https://twitter.com/garockus"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  resume_instagram_url:         "https://www.instagram.com/garockus/"
  resume_website_url:           "https://sinnix.de"
  resume_xing_url:              "https://www.xing.com/profile/Florian_Miess/cv"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
